### ISSUE TITLE
Another use of the scheduler

### ISSUE THREAD

**Issue by ponythewhite** [enragedginger/akka-quartz-scheduler#1]
Hello,

In my projects I am currently using [akka-quartz](https://github.com/theatrus/akka-quartz).

I would love to have all the benefits you are describing (especially the singleton-ity).

But I need to dynamically add jobs with custom schedules.

E.g. a message like this:

```
case OrderWithExpiry(order: Order, goodTill: Long) => {
    enqueueOrder(payload)
    val dt = new DateTime(goodTill)
    val cronString = s"${dt.getSecondOfMinute} ${dt.getMinuteOfHour} ${dt.getHourOfDay} ${dt.getDayOfMonth} ${dt.getMonthOfYear} ? ${dt.getYear}"
    quartz ! AddCronSchedule(self, cronString, ExpireOrder(order), false)
}
```

IMHO a quite basic use case is that some messages received by the system contain the definition of the cron schedule.

From what I understand, you explicitly ban this scenario - but maybe there is another way I could achieve my results assuming your approach? Rewriting textfile configuration would be very ineffective.

Best,

--
Jacek

**Comment by cdittberner** [comment]
+1

**Comment by enragedginger** [comment]
Thanks for the suggestion.  This topic was created long before I inherited the project.  Is this still a feature that you would like to see us add?  You can call createSchedule on QuartzSchedulerExtension to add your own schedules at runtime if I'm not mistaken.

**Comment by enragedginger** [comment]
I'm going to close this issue. It looks like this functionality has existed since [this pull request / issue](https://github.com/enragedginger/akka-quartz-scheduler/issues/6) was resolved.
