### ISSUE TITLE
Cancel/Delete all job schedules

### ISSUE THREAD

**Issue by amdelamar** [enragedginger/akka-quartz-scheduler#105]
Can we get a function added to cancel/remove all job schedules? There are a few functions I see that don't quite do this yet:
- `deleteJobSchedule(name: String)` -> Requires knowning the schedule name.
- `suspendAll()` -> Pauses but doesn't remove job schedules.
- `shutdown(waitForJobsToComplete: Boolean = false)` -> Looks like what I want but comment says "The scheduler cannot be re-started." so I'm not sure if I can reuse the scheduler or not.

It'd be great addition to have a `cancelAll()` function.

**Comment by amdelamar** [comment]
I'd be happy to make a PR, if that helps.

**Comment by enragedginger** [comment]
@amdelamar Feel free to create a PR with some tests and I'll take a look at it!

**Comment by felipebonezi** [comment]
> I'd be happy to make a PR, if that helps.

It will, waiting for it. 😁

**Comment by amdelamar** [comment]
I got the 'Ok' from my workplace, so I put up a PR.
I decided it should be `deleteAll()` since `cancelAll()` is akin to `suspendAll()` and that's implemented already.
