### ISSUE TITLE
Persistance Jobs

### ISSUE THREAD

**Issue by SarpongAbasimi** [enragedginger/akka-quartz-scheduler#119]
Hey, I am looking through the source code of akka-quartz-scheduler and came across this line.

```scala
  lazy protected val jobStore: JobStore = {
    // TODO - Make this potentially configurable,  but for now we don't want persistable jobs.
    new RAMJobStore()
  }
```

I am just a bit curious, why was the decision taken to not want persistable jobs.

**Comment by SarpongAbasimi** [comment]
@enragedginger I am closing this but please feel free to still answer this thanks.

**Comment by enragedginger** [comment]
Hi @SarpongAbasimi,
I inherited this project several years ago after that part of the code was written so I'm unfortunately not familiar with the rationale behind it.
