### ISSUE TITLE
Need scheduler version of 1.2.0-akka-2.2.x

### ISSUE THREAD

**Issue by yvsubhash** [enragedginger/akka-quartz-scheduler#12]
Hi,
Our product is using the play framework and akka with version 2.2.2. I would like to try this scheduler with our product. We are not planning to upgrade our akka version any time soon. Can you please publish 1.2.0-akka-2.2.x version of the scheduler.

**Comment by enragedginger** [comment]
Hi yvsubhash,

Is this request still valid? Would you still like a build for Akka 2.2?

**Comment by enragedginger** [comment]
I'm going to mark this as closed. Let me know if you still need this build.
