### ISSUE TITLE
Use actorSelection instead of actorFor

### ISSUE THREAD

**Issue by froque** [enragedginger/akka-quartz-scheduler#13]
It seems ActorRef is deprecated. Could this project change to ActorSelection? 

http://doc.akka.io/docs/akka/2.2-M3/project/migration-guide-2.1.x-2.2.x.html#migration-2-2-actorselection

**Comment by ktoso** [comment]
Typo? `ActorRef` is fine, `actorFor` is deprecated :-)

**Comment by froque** [comment]
Maybe I'm mixing different concepts, but my problem is that if the actor dies the scheduler cannot get a new reference, because it's using ActorRef and not ActorSelection so it cannot send a message to the new actor.

**Comment by ktoso** [comment]
Yes, that is correct.
I wouldn't say ActorRefs are "deprecated" - they're perfectly fine, just that they have a slightly different role "the exact actor", whereas actor selection is "send to anyone who's living under this address currently". In the context of this project selection probably indeed makes more sense :-)

Hope this helps clear up any confusion I might have caused! :-)

**Comment by enragedginger** [comment]
Switching to ActorSelection makes sense in my mind.  If you create a pull request complete with tests, I'll consider it for merging.

**Comment by enragedginger** [comment]
This is now fixed and will be included in the next release.
