### ISSUE TITLE
Ignoring the first message

### ISSUE THREAD

**Issue by FrEaKmAn** [enragedginger/akka-quartz-scheduler#15]
Hi

I'm using to schedule daily cron jobs (run at midnight), but I want to somehow ignore the first message (when apps starts). Is there a way to add this?

**Comment by enragedginger** [comment]
I'm not entirely sure I understand what you're referencing.  Do you have a code snippet that you can share to illustrate your issue?

My apologies for the belated response.

**Comment by enragedginger** [comment]
Closing this issue. Please reopen if it is still a request.
