### ISSUE TITLE
The scheduler never triggers actors if any calendar is associated

### ISSUE THREAD

**Issue by WeiZheng** [enragedginger/akka-quartz-scheduler#16]
Hi Stephen Hopper,

The scheduler is really very useful, especially for applications which have large amount of actor tasks to schedule in the background.

However, do you notice a post on stackoverflow: http://stackoverflow.com/questions/19727325/akka-quartz-scheduler-never-triggers-my-actor? I also encounter this problem and after checking the source code, still have no clue on how to fix it.

Regards
Wei Zheng

**Comment by pgorin** [comment]
Hi Wei, the problem occurs during calendars initialization.
Check line 245 in QuartzSchedulerExtension class:
scheduler.addCalendar(name.toUpperCase, calendar, true, true)

The calendar is added using UpperCase, so Quartz never finds it, producing that no job is triggered then.
If you define your calendar in akka config using UpperCase name it should work.

**Comment by enragedginger** [comment]
I don't think casing is the issue.  The schedule method on QuartzSchedulerExtension performs the lookup based on the uppercased value of the schedule name.  If the schedule was not found when calling "schedule," an IllegalArgumentException would be thrown.

Wei,
Can you post the output from Quartz that you're seeing in your logs?

**Comment by WeiZheng** [comment]
Hi Stephen Hopper,

I've tested the version 1.4.0-akka-2.3.x on the latest play framework 2.4.2 and everything works fine.

I am not sure if the original problem is due to my carelessness on cron expression or whatever, please close that issue. :)

Regards,
Wei Zheng

**Comment by enragedginger** [comment]
Thanks for the update! Let me know if you run into anymore issues!
