### ISSUE TITLE
delete a job which is not running

### ISSUE THREAD

**Issue by tl3shi** [enragedginger/akka-quartz-scheduler#20]
I am wondering if there is any way to delete a job which is not running~
After review the code, I found that I can access it by using 
```QuartzSchedulerExtension. schedules -= (key) ```
However, the key is not what I have created by 
```QuartzSchedulerExtension.createSchedule(key, description....)```
I have to uppercased the key. (As well as some other operations related to the key, as follows)

```scala
 if (scheduler.schedules.contains(jobName)){
      if (scheduler.runningJobs.contains(jobName))
        scheduler.cancelJob(jobName)
      else
        scheduler.schedules -= (jobName) //delete
    }
```

Hope that you can giving some explanation.

**Comment by enragedginger** [comment]
@tl3shi I'm not sure that I follow. Uppercasing your keys is required as all entries in that map are forced to uppercase. I think the code you have there should work. If there's something you'd like to see included in the library, feel free to submit a pull request.

**Comment by enragedginger** [comment]
I'm going to close this due to inactivity. If you're still experiencing issues, feel free to update this thread and re-open.
