### ISSUE TITLE
It's not possible to restart scheduler from standby mode by using the start method

### ISSUE THREAD

**Issue by livingsoft** [enragedginger/akka-quartz-scheduler#21]
It seems like when you call, standby, the scheduler is in standby mode, however, the isStarted flag is still true. As such, since the start method only looks at isStarted flag, standby is never able to satisfy the conditions to restart scheduler.

P.S. I love this library. It's saving me so many lines of code.

**Comment by enragedginger** [comment]
I think this is working as expected. For this functionality, we're really just wrapping what's offered by the Quartz Scheduler. From [the Quartz docs](http://quartz-scheduler.org/api/previous_versions/2.1.0/org/quartz/Scheduler.html#start%28%29) on ```isStarted```:

> Whether the scheduler has been started.
> Note: This only reflects whether start() has ever been called on this Scheduler, so it will return true even if the Scheduler is currently in standby mode or has been since shutdown. 

For your use case, try checking the ```isInStandbyMode``` flag. For more on the differences between ```standby``` + ```start``` vs ```pauseAll``` vs ```resumeAll```, see [this SO post](http://stackoverflow.com/questions/3650539/what-is-the-difference-between-schedulers-standby-and-pauseall).
