### ISSUE TITLE
Schedule job for only once or with dynamic timer

### ISSUE THREAD

**Issue by ChetanBhasin** [enragedginger/akka-quartz-scheduler#22]
Is it possible to schedule jobs which will be executed only once after a particular amount of time? Or schedule jobs which for which the time hasn't been specified in a strict configuration?

**Comment by mingchuno** [comment]
why not use context.system.scheduler.scheduleOnce() ?
Scheduler — Akka Documentation
http://doc.akka.io/docs/akka/snapshot/scala/scheduler.html

**Comment by ChetanBhasin** [comment]
Because it's not persistent.

**Comment by enragedginger** [comment]
@ChetanBhasin I'm not sure that I understand your situation. Like @mingchuno said, my first inkling would be to point you to `scheduleOnce`. Can you explain why this won't work?

**Comment by ChetanBhasin** [comment]
@enragedginger Because if the actor system had to be restarted before the job was scheduled, the job will be lost.

**Comment by mingchuno** [comment]
@ChetanBhasin Do not abuse quartz-scheduler for this task. I think this should be the application logic to persist the `scheduleOnce` job and replay upon actor restart.

**Comment by enragedginger** [comment]
I agree with @mingchuno. This sounds like logic that should be a part of your application and not necessarily the library. If you feel this is not the case, feel free to submit a pull request and I'll review it.
