### ISSUE TITLE
Enhancement to support Akka-2.4.0

### ISSUE THREAD

**Issue by kwidjaja1312** [enragedginger/akka-quartz-scheduler#23]
Hi Guys, first of all i would like to thank you all for this amazing library. Since one of my app is depends heavily on this scheduler, i would like to know whether there will be an enhancement to support Akka-2.4.0? The reason is i need to implement `Akka Persistence` which is based on Akka-2.4.0 and there is no documentation mentioning that this library can work properly with Akka-2.4.0.

**Comment by ktoso** [comment]
We made 2.3 binary compatible with 2.4.x so you should be able to just use 2.4.

**Comment by enragedginger** [comment]
The library should be compatible with Akka 2.4. However, the next release will explicitly support Akka 2.4

**Comment by enragedginger** [comment]
The newest release supports Akka 2.4 (as of 124debdeb24cb0e787c29c49f38c5c467107eed7). The dependency on Akka is marked as "provided", so you'll want to specify the version manually. If you run into any issues, please let us know.

**Comment by kwidjaja1312** [comment]
Thanks, will try it as soon as my migration to playframework 2.5 is successful as i have to upgrade the akka version to 2.4.2 explicitly. Appreciate for the effort.
