### ISSUE TITLE
Schedule job using cron expression as a string instead of from configuration

### ISSUE THREAD

**Issue by anandp504** [enragedginger/akka-quartz-scheduler#24]
Is there a provision to schedule a job directly using cron expression instead of specifying the cron expression in the configuration file? As the documentation suggests, currently this is not possible, is it?

**Comment by julienlafont** [comment]
You can programmatically create a schedule with [`scheduler.createSchedule`](https://github.com/enragedginger/akka-quartz-scheduler/blob/aa480993867225389e3f1800be82739247c36e21/src/main/scala/QuartzSchedulerExtension.scala#L187).

**Comment by enragedginger** [comment]
@julienlafont is right. You can call ```scheduler.createSchedule``` to create the schedule with the desired cron expression and then schedule jobs against that schedule by calling ```scheduler.schedule``` with the same name key you passed to ```scheduler.createSchedule```.
