### ISSUE TITLE
Messages firing at wrong time

### ISSUE THREAD

**Issue by kdoomsday** [enragedginger/akka-quartz-scheduler#26]
I have a cron job scheduled with
```
akka.quartz.schedules {
  work {
    description = "Do something every hour on business hours"
    expression = "0 0 8-17 ? * MON-FRI"
  }
}
```
Instead of triggering on the hour, it's doing so at half past. It is possible that my country's timezone has something to do with this, because we are at -04:30 UTC, meaning we are displaced half an hour from what is usually expected.

Clearly I could adjust the time in the cron expression, but that would cause confusion to anyone trying to figure out when things are supposed to happen. Any help would be appreciated.

**Comment by mingchuno** [comment]
You can specify your timezone like:
```
akka.quartz.schedules {
  work {
    timezone = "America/Caracas"
    description = "Do something every hour on business hours"
    expression = "0 0 8-17 ? * MON-FRI"
  }
}
```

**Comment by kdoomsday** [comment]
That worked perfectly, thanks!. I wonder, though, is there a particular reason it used a different timezone than the one configured for the system?

**Comment by kdoomsday** [comment]
Thanks for the help, by the way! Closing this.
