### ISSUE TITLE
Is it possible to use with Java?

### ISSUE THREAD

**Issue by phelipemaia** [enragedginger/akka-quartz-scheduler#30]
I have an akka project written in Java. So, is it possible to use akka-quartz-scheduler in a java project? Or should I build and create a package to use in my project?

**Comment by enragedginger** [comment]
We don't officially support Java. However, I don't know of any reasons as to why this library will not work with Java. Go ahead and give it a shot and let me know what you find.

**Comment by gslowikowski** [comment]
I'm using it with Java in Play! Framework project without problems.

**Comment by enragedginger** [comment]
Thank you, @gslowikowski

@phelipemaia Let us know if you run into any issues. I'm closing this for now.

**Comment by gslowikowski** [comment]
I initialize it this way:
```java
import com.typesafe.akka.extension.quartz.QuartzSchedulerExtension;
import com.typesafe.akka.extension.quartz.QuartzSchedulerExtension$;

QuartzSchedulerExtension ext = QuartzSchedulerExtension$.MODULE$.apply(system);
```
where `system` is `ActorSystem`.

Actually I don't know, why it works, because this extension [requires ExtendedActorSystem](https://github.com/enragedginger/akka-quartz-scheduler/blob/release-1.4.0/src/main/scala/QuartzSchedulerExtension.scala#L24)

:)

**Comment by ktoso** [comment]
Hi guys, the "not usable from Java" is an actual omission in the impl :-)
I've submitted a PR which fixes it so no-one has to do the `MODULE$` hack, please have a look!

https://github.com/enragedginger/akka-quartz-scheduler/pull/38

**Comment by phelipemaia** [comment]
Perfect.. Thanks @ktoso @gslowikowski and @enragedginger 

sorry for the delay...
