### ISSUE TITLE
Can't get a schedule to work with a weekly calendar

### ISSUE THREAD

**Issue by avive** [enragedginger/akka-quartz-scheduler#34]
I'm using quartz scheduling in a scala project. Scheduling works fine unless a calendar is specified for a schedule. In that case, the task is never triggered by the scheduler. Example:

`akka {
  quartz {
    defaultTimezone = "America/New_York"
    schedules {
      WeeklyEmailSchedule {
        description = "7:00 am every Friday"
        expression = "0 16 11 ? * FRI"
      }
      DailyEmailSchedule {
        description = "7:00 am every day"
        expression = "0 0 7 ? * *"
        calendar = "DailyCalendar"
      }
    }
    calendars {
      DailyCalendar {
        type = Weekly
        description = "Daily excluding friday"
        excludeDays = [6]
        excludeWeekends = false
      }
    }
  }
}`

If I comment out the line: `calendar = "DailyCalendar"` then everything works as expected. What am I doing wrong? Is my calendars prop invalid in any way?
Library version:
 "com.enragedginger" % "akka-quartz-scheduler_2.11" % "1.4.0-akka-2.3.x"

Thanks so much!

**Comment by mingchuno** [comment]
```
akka {
  quartz {
    schedules {
      name-it-as-you-want {
        timezone = "Asia/Nicosia"
        description = "A cron job that fires off every midnight 00:02 in CY time"
        expression = "0 2 0 * * ?"
        calendar = "OnlyBusinessHours"
      }
    }
  }
}
```
something like this should work

**Comment by avive** [comment]
@mingchuno if you look at my code above this is basically what I had but it won't fire unless I comment out calendar and my calendar is just set to exclude friday for my daily tasks.

**Comment by avive** [comment]
I'll answer my own question - in the version I'm using calendar names must be uppercase only. Once I changed the calendar name to DAILYCALENDAR things started working properly.

**Comment by pawelkaczor** [comment]
This is a bug "calendar names must be uppercase only. I lost 2 hours finding out what's going on.
