### ISSUE TITLE
How to recover fail scheduled job?

### ISSUE THREAD

**Issue by harmeetsingh0013** [enragedginger/akka-quartz-scheduler#43]
I am using akka-actor system, and send message to my actor with in specific time. akka-quartz-scheduler is amazing library for schedule chron jobs easily. But if my scheduler node goes down, how can i recover my scheduler? because my scheduling job is really important. I know, for this, we need a clustering, but is there any way using akka-quartz-scheduler for recover scheduled jobs?

**Comment by enragedginger** [comment]
Hello,

This project doesn't have any sort of functionality to do what you're proposing, but I think there's still things you can do to to make this work for your use case.

In the Akka world, the default behavior on actor failure is to simply restart. If you're looking to recover from full system outages / reboots, you could take a look at Akka's persistence library and see if that meets your needs. However, that only saves you once your system comes back online. If the node goes offline permanently, then you're out of luck. If you're concerned about that, or if you're concerned about your jobs not running while the node is down, then I would suggest looking into Akka clustering with failover.

Does that make sense?

**Comment by enragedginger** [comment]
Marking this as closed. Please reopen if this is still an issue.
