### ISSUE TITLE
Default timezone

### ISSUE THREAD

**Issue by cpoissonnier** [enragedginger/akka-quartz-scheduler#47]
Hello,

Just a quick question ... Don't you think that timezone should be set automaticaly to the system timezone? 

I spent 2 hours figuring out why my job wasn't triggered ;)

Thanks for this great extension !

**Comment by niiamon** [comment]
How did you set the defaultTimezone? Doing this doesn't work:

akka {
  ...
  quartz {
    defaultTimeZone = "America/Los_Angeles"
...

**Comment by cpoissonnier** [comment]
```
akka {
  threadPool {
    threadCount = 3
    threadPriority = 5
    daemonThreads = true
  }
  quartz {
    schedules {
      checkEndDate {
        description = "Check expiring convention and accounts"
        expression = "0 0 6 ? * *"
        timezone = "Europe/Paris"
      }
    }
  }
}
```

**Comment by enragedginger** [comment]
Marking this as closed due to lack of a response.
