### ISSUE TITLE
Can't restart a job put on standby

### ISSUE THREAD

**Issue by zoltanmaric** [enragedginger/akka-quartz-scheduler#48]
After suspending the scheduler, it can no longer be resumed.

```scala
val scheduler = PatchedQuartzSchedulerExtension(system)
scheduler.standby()
scheduler.start() // this line logs a warning saying it's already started
```

This is because the `start` method only checks the value of the `isStarted` field, but not the `isInStandbyMode` field.

Proposed patch:

```scala
  def start(): Boolean =
    if(isStarted && !isInStandbyMode) {
      log.warning("Cannot start scheduler, already started.")
      false
    } else {
      scheduler.start()
      true
    }
```

**Comment by zoltanmaric** [comment]
I can submit a pull request later.

**Comment by enragedginger** [comment]
This sounds reasonable to me. Does anyone else have any comments on this?

@zoltanmaric If you submit a pull request, I'll review it.

Thanks!

**Comment by enragedginger** [comment]
Marking as closed due to inactivity.
