### ISSUE TITLE
Can't remove schedule from QuartzSchedulerExtension directly.

### ISSUE THREAD

**Issue by phaith** [enragedginger/akka-quartz-scheduler#52]
I've problem to recreate schedule with different cron expression. I can use ` QuartzSchedulerExtension(system).createSchedule(xxxx)` then I can use `QuartzSchedulerExtension(system).schedule(xxxx)` for the first time. However, I've to handle it in different way to recreate it by using `QuartzSchedulerExtension(context.system).rescheduleJob(xxx)`.

Should `cancelJob` also call `removeSchedule` so that we can recreate it again later?

**Comment by enragedginger** [comment]
I'm not sure I understand exactly what you're getting at. Can you explain in a bit more detail? If this is still a desired feature, can you submit a PR with tests?

**Comment by enragedginger** [comment]
Marking this as closed due to inactivity.
