### ISSUE TITLE
Publish akka 2.5.x release?

### ISSUE THREAD

**Issue by markschaake** [enragedginger/akka-quartz-scheduler#55]
Hi, thanks for maintaining this great library!

It looks like the project has already been [updated for akka 2.5.x](https://github.com/enragedginger/akka-quartz-scheduler/commit/ffc9a8f415434fd123033c3cff207ac9014c28eb), but there isn't a release published to [maven central](https://repo1.maven.org/maven2/com/enragedginger/akka-quartz-scheduler_2.12/) yet. Is there a reason for the delay?

Thanks,

Mark

**Comment by enragedginger** [comment]
Typically, we bump the build for a new version of Scala, Akka, or some arbitrary libray. And then I say to myself, "I should publish a new build soon." And then I forget to do it until someone comes along and asks nicely.

Anyhow, version `1.6.1-akka-2.5.x` has been "release" and should be available through Maven Central in the next 24 hours.
