### ISSUE TITLE
Upgrade to v2.3.0 of quartz

### ISSUE THREAD

**Issue by vinayakpathak** [enragedginger/akka-quartz-scheduler#61]
It's still using 2.2.3, which is causing conflicts from its transitive dependencies.

**Comment by enragedginger** [comment]
I've merged the PR. For future reference though, you can just manually specify some other version of Quartz in whatever dependency management system you're using.

**Comment by vinayakpathak** [comment]
Thanks! Yes, I did end up doing that. To give you some more detail on the issue:

The older version of quartz used an older version of c3p0, which was hosted in _a different group_ on maven than the new version of c3p0. My application used the new version of c3p0. The different group confused sbt into thinking that they are actually different libraries and it tried to include both of them, thus causing a conflict.

This was hard to diagnose and changing the version in akka-quartz itself might save people from experiencing the same problem.

**Comment by enragedginger** [comment]
Wow. That's rough. Yeah, transitive dependency conflicts are the worst.
