### ISSUE TITLE
Support for akka 2.5 and scala 2.11

### ISSUE THREAD

**Issue by OlafurD** [enragedginger/akka-quartz-scheduler#66]
Is it possible to support akka 2.5 with scala 2.11?

**Comment by urieli** [comment]
See https://github.com/enragedginger/akka-quartz-scheduler/issues/64

**Comment by enragedginger** [comment]
Hi @OlafurD, @urieli is correct, this is a duplicate of #64. You should be able to use the Akka 2.4, Scala 2.11 build of the project just fine with Akka 2.5.
