### ISSUE TITLE
RescheduleJob only accepts ActorRef

### ISSUE THREAD

**Issue by rustyfetty** [enragedginger/akka-quartz-scheduler#67]
Why does the rescheduleJob in QuartzSchedulerExtension only accepts ActorRef in its parameters?I prefer to use ActorSelection over ActorRef. That way if the actor dies, you can get the new path from the ActorSelection. Can you make it also accept ActorSelection?

**Comment by enragedginger** [comment]
@rustyfetty Hello, sorry it took me so long to get around to this, but the library now supports `ActorSelection`.
