### ISSUE TITLE
Scheduler stops after 8 repetitions

### ISSUE THREAD

**Issue by walter-torricos-mojix-com** [enragedginger/akka-quartz-scheduler#68]
I made some tests with the following cron expression
akka {
  quartz {
    schedules {
      Every30Seconds {
        description = "A cron job that fires off every 30 seconds"
        expression = "*/30 * * * * ?"
      }
    }
  }
}
I played around with different values for the expression but it always stops after 8 repetitions.

I'm importing this version of the library:
"com.enragedginger" %% "akka-quartz-scheduler" % "1.6.0-akka-2.4.x"
Scala version 2.11.6 and play version 2.5.12

**Comment by mingchuno** [comment]
@walter-torricos-mojix-com can you create a reproducer repo for us to test?

**Comment by walter-torricos-mojix-com** [comment]
@mingchuno thanks but I'm going to close this issue. There is no problem with your library, the problem is that I inherited from a base class actor that we have and which has a bug and is locking after some time, that's why my actor stopped being called. Again thanks for your help and sorry for the inconvenience.

**Comment by enragedginger** [comment]
Good to know. Thank you!
