### ISSUE TITLE
release for Scala 2.11.x and Akka 2.5.x

### ISSUE THREAD

**Issue by olambo** [enragedginger/akka-quartz-scheduler#72]
Any possibility of a build for Scala 2.11.12 and Akka 2.5.12
reason: It looks like Spark is not upgrading to Scala 2.12.x at all.

**Comment by enragedginger** [comment]
Hi @olambo, sorry it took me so long to get around to this. Spark's insistence on staying behind the times on Scala versions has always bothered me. Regardless, I pushed a build a few minutes ago: `libraryDependencies += "com.enragedginger" %% "akka-quartz-scheduler" % "1.7.0-akka-2.5.x"`. Let me know if it doesn't work for you.
