### ISSUE TITLE
Custom calendars

### ISSUE THREAD

**Issue by schleumer** [enragedginger/akka-quartz-scheduler#73]
Shouldn't it be possible to add custom calendars? I mean, actually calendars are just configurations with no possibility to "customization", like exclude weekends in monthly calendars(it's useful to pick the first business day of a month), because it's all inside `QuartzCalendars` and `QuartzCalendars` is accessed directly by `QuartzSchedulerExtension`, although it's possible to create custom calendars if extends `QuartzSchedulerExtension` and access `scheduler.addCalendar` internally, i don't think it's a bad practice, or is it?

**Comment by enragedginger** [comment]
Hi @schleumer, you should be able to add custom calendars in the same config file as your schedules. From the docs:

`There are two 'primary' sub-blocks of the akka.quartz configuration, which are schedules and calendars.`
