### ISSUE TITLE
akka-quartz-scheduler with java

### ISSUE THREAD

**Issue by sleski** [enragedginger/akka-quartz-scheduler#74]
Hi, I just wanted to use your lib with playframework-java app.
I created sample project - https://github.com/sleski/play-akka-quartz-example
I created two actors which should be triggered by cron scheduler every 10seconds.
But this does not work. App starts, from log looks like it should be triggered:

`[INFO] from com.typesafe.akka.extension.quartz.QuartzSchedulerExtension in application-akka.actor.default-dispatcher-2 - Setting up scheduled job 'HELLO_ACTOR', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@746cb637'`

`[INFO] from com.typesafe.akka.extension.quartz.QuartzSchedulerExtension in application-akka.actor.default-dispatcher-2 - Setting up scheduled job 'CLEANUP_ACTOR', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@34d78b1c'`

I did not find any informations how to configure it in play java app, may some configuration is missing?! 

I will be grateful for any tip/help.

**Comment by mtrna** [comment]
Hi Sławek, the correct cron expression for 10 second interval would be:
`expression = "0/10 * * ? * * *"`

**Comment by sleski** [comment]
Hi Michal (@mtrna ), 
thanks for info, yes, my cron expression was not correct. But this still not solve my question :/

**Comment by mtrna** [comment]
Hi Sławek, perhaps this PR addresses your question? https://github.com/sleski/play-akka-quartz-example/pull/1

**Comment by sleski** [comment]
Hi Michael,
thanks for PR, I will check it later.

**Comment by sleski** [comment]
Hi Michael,
yes, it works :-) 

Thanks a lot for your help!
