### ISSUE TITLE
Make QuartzSchedulerExtension#removeSchedule public

### ISSUE THREAD

**Issue by nebehr** [enragedginger/akka-quartz-scheduler#77]
Since ```createSchedule``` method is public it makes sense to make ```removeSchedule``` public as well. Currently a schedule can be deleted by removing entry from ```schedules``` map but ideally IT should be made private instead.

https://github.com/enragedginger/akka-quartz-scheduler/blob/master/src/main/scala/QuartzSchedulerExtension.scala#L241

**Comment by enragedginger** [comment]
@nebehr Thanks for the suggestion. I can see the value of this. It's a bit more complicated than simply removing the schedule as you'd want to cancel the associated jobs first. Feel free to submit a PR for this.

**Comment by vendethiel** [comment]
Why close the issue? Even if you're waiting for someone to contribute the feature, it's actually useful to have that issue open.

**Comment by enragedginger** [comment]
@vendethiel I'm not waiting for someone to contribute the feature at this point. If someone wants to volunteer to do it and submit the PR, they're welcome to do it. I prefer to use issues on GitHub projects for true issues with the software or possibly active feature development. The "projects" section of each project exists specifically to track future work.
