### ISSUE TITLE
Rebuild on Scala 2.12.7 Mandatory

### ISSUE THREAD

**Issue by twoodhouse** [enragedginger/akka-quartz-scheduler#78]
Hi! I am using this library, but it is now broken for Java 11.
Any QuartzSchedulerExtension.get(....) java calls fail with "reference to get is ambiguous"

For info, see this post:  https://contributors.scala-lang.org/t/library-authors-rebuild-on-2-12-7-to-improve-callability-from-java-on-jdk-11/2465

If you could rebuild on Scala 2.12.7, it will fix the issue.
It would be awesome if you could do this soon, as I must transition to Java 11 in the near future for other reasons. Thanks!

**Comment by enragedginger** [comment]
Hello @twoodhouse ,
Thanks for reporting this. I don't have any Java projects that are using this library, so I don't have an easy way of testing this out. Can you:

- Clone down this project
- Update the Scala version in build.sbt from 2.12.4 to 2.12.7
- Build the project (with either `sbt install` IIRC)
- Test against your local Java 11 project
- And then let me know if that resolves the issue

**Comment by twoodhouse** [comment]
When you get the chance, I would appreciate a maven jar for this (built with scala 2.12.7). Thanks for the support!

**Comment by enragedginger** [comment]
@twoodhouse I've published version 1.7.1 of the akka-quartz-scheduler which should fix your issue.
